default: &default
  adapter: sqlite3
  database: gat_devtest_development
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: gat_devtest_test

production:
  <<: *default
  database: gat_devtest_production
